### ISSUE TITLE
FileNotFoundException is thrown for any PS commands

### ISSUE THREAD

**Issue by dilshaat** [vors/jupyter-powershell#36]
After starting the Powershell Kernel, and any powershell commands are throwing the FileNoteFoundException:

```powershell
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\powershell_kernel\kernel.py", line 62, in do_execute
    self.__createProxy()
  File "C:\Python38\lib\site-packages\powershell_kernel\kernel.py", line 51, in __createProxy
    repl = subprocess_repl.SubprocessRepl([powershell_command, '-noninteractive', '-noprofile', '-File', '-'])
  File "C:\Python38\lib\site-packages\powershell_kernel\subprocess_repl.py", line 28, in __init__
    self.popen = Popen(cmd, bufsize=1,
  File "C:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by dilshaat** [comment]
It turned out that I did not run:
```Python
python -m powershell_kernel.install
```
This is resolved. Closing.
