### ISSUE TITLE
Incomplete cell hangs kernel

### ISSUE THREAD

**Issue by vors** [vors/jupyter-powershell#9]
Incomplete cells currently hang the kernel. I.e. `(`
Unfortunately, powershell input redirection doesn't allow to enter `\n` few more times to get incomplete input error. But we should be able to handle it better.

**Comment by vors** [comment]
I put a mitigation detection in the kernel, because we can detect the hang, we just cannot do anything about it: there is nothing we can send powershell process to abort operation or do anything else to get the error message.

**Comment by vinayak-kaniyarakkal** [comment]
**In the console** The system cannot find the file specified
**In the browser**  The kernel appears to have died. It will restart automatically.

**Content of ~/AppData/Roaming/jupyter/kernels/powershell/kernel.json**

`
{
    "argv": [
	"C:\\archive2\\Vinayak\\rnd\\platform\\anaconda\\python.exe",
	"-m",
	"powershell_kernel",
	"-f",
	"{connection_file}"
    ],
    "display_name": "PowerShell",
    "env": {"powershell_command": "pwsh"},
    "language": "powershell"
}
`

**Full traceback in console.**
>  Traceback (most recent call last):
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\site-packages\powershell_kernel\__main__.py", line 3, in <module>
>     IPKernelApp.launch_instance(kernel_class=PowerShellKernel)
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
>     app.initialize(argv)
>   File "<decorator-gen-124>", line 2, in initialize
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
>     return method(app, *args, **kwargs)
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\site-packages\ipykernel\kernelapp.py", line 454, in initialize
>     self.init_kernel()
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\site-packages\ipykernel\kernelapp.py", line 365, in init_kernel
>     user_ns=self.user_ns,
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
>     inst = cls(*args, **kwargs)
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\site-packages\powershell_kernel\kernel.py", line 50, in __init__
>     repl = subprocess_repl.SubprocessRepl([powershell_command, '-noprofile', '-File', '-'])
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\site-packages\powershell_kernel\subprocess_repl.py", line 29, in __init__
>     stderr=subprocess.STDOUT, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\subprocess.py", line 707, in __init__
>     restore_signals, start_new_session)
>   File "C:\archive2\Vinayak\rnd\platform\anaconda\lib\subprocess.py", line 990, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> [I 14:30:56.125 NotebookApp] KernelRestarter: restarting kernel (1/5)
> WARNING:root:kernel 334f9cf8-1836-4623-bf40-a25fb4ecc6a2 restarted
>
